"""init

Revision ID: 74ef600be7ed
Revises:
Create Date: 2025-08-20 18:16:19.782176

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "74ef600be7ed"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
