"""baseline_existing_schema

Revision ID: 8b4a05c39346
Revises: 
Create Date: 2026-02-20 13:07:27.126252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b4a05c39346'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.alter_column('users', 'user_type',
               existing_type=postgresql.ENUM('client', 'admin', name='user_type_enum'),
               comment=None,
               existing_comment='User type (client/admin) - REQUIRED with default',
               existing_nullable=False)
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('services', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_client_id_fkey', 'orders', 'users', ['client_id'], ['id'])
    op.create_foreign_key('orders_service_id_fkey', 'orders', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###
