"""add middle_name to users

Revision ID: 91d97cb4062d
Revises: 8b4a05c39346
Create Date: 2026-02-20 13:16:38.142107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91d97cb4062d'
down_revision: Union[str, Sequence[str], None] = '8b4a05c39346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###
